### PR TITLE
fix: avoid reading undefined

### LINKED ISSUE #164: Cannot read properties of undefined (reading 'message')
### Reporting a bug?

Cannot read properties of undefined (reading 'message')

### Expected behavior

Cannot read properties of undefined (reading 'message')

### Reproduction

I18n.ts

```
import { createI18n } from 'vue-i18n';
import messages from '@intlify/vite-plugin-vue-i18n/messages';

const i18n = createI18n({
  legacy: false,
  locale: 'en',
  messages
});

export default i18n;

```

vite.config.ts

```
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueI18n from '@intlify/vite-plugin-vue-i18n';
import eslint from 'vite-plugin-eslint';
import { resolve } from 'path';
import path from 'path'

export default defineConfig({
  plugins: [
    vue(),
    eslint({
      fix: true
    }),
    vueI18n({
      include: path.resolve(__dirname, './src/locales/**')
    })
  ],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      '@assets': resolve(__dirname, './src/assets'),
      '@layouts': resolve(__dirname, './src/layouts')
    }
  }
});

```

error

```
Cannot read properties of undefined (reading 'message')
12:26:54 PM [vite] Internal server error: Cannot read properties of undefined (reading 'message')
      at Object.newOptions.onError (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/codegen.js:102:48)
      at Object.newOptions.onError (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
      at newOptions.onError (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/codegen.js:102:36)
      at emitError (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:866:13)
      at parsePlural (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1088:13)
      at parseResource (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1101:20)
      at Object.parse (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1111:21)
      at baseCompile (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/message-compiler/dist/message-compiler.cjs.js:1425:24)
      at generateMessageFunction (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/codegen.js:105:67)
      at Object.enterNode (/Users/maksimdrazdou/Projects/Vue3/esim/node_modules/@intlify/bundle-utils/lib/json.js:110:89)
```

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
@intlify/vite-plugin-vue-i18n
```

### Screenshot

_No response_

### Additional context

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).

### PR DESCRIPTION
**Pull request by kentahama**
fix #164

### CODE REVIEW

**Comment by kentahama** [comment]
Thank you for quick review.
I could reproduce the error #164 in [this repo](https://github.com/kentahama/reproduce-vue-i18n-yaml), and I edited `node_modules/@intlify/bundle-utils/lib/codegen.js` directly then I got an appropriate error.
But I added the same yaml to the unit test, it did not cause an error.

**Comment by kazupon** [comment]
Thank you for your quick reply & reproduction repo!

I could face this issue on your repo.

>But I added the same yaml to the unit test, it did not cause an error.

Hmm, 🤔 That’s weird.
This is an issue with `@intlify/bundle-utils`.
So we have thought we could reproduce it by adding the fixture for this error [here](https://github.com/intlify/bundle-tools/tree/main/packages/bundle-utils/test/fixtures/codegen) and adding the unit test.

Could you give us to your test codes in commits please?

**Comment by kentahama** [comment]
I added the unit test.

I thought I got an appropriate error message by avoiding reading undefined during parsing yaml but that was probably not.
I got this error
image
this means parsing yaml works well, but something was wrong after parsing.

This is why the unit test passes.

**Comment by kazupon** [comment]
Thank you for your unit test!

I've debugged about this issue
It's a mystery why the Error message notified by the message compiler in `onError` is `undefined`.
The underlying cause with this issue is that error handling in unplugin-vue-i18n is not good.
This issue has also been reported as an issue in nuxtjs/i18n, and I will try to fix this issue.

BTW, `@` is special character in vue-i18n v9
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#special-characters

You can avoid with using literal interpolation
https://vue-i18n.intlify.dev/guide/essentials/syntax.html#literal-interpolation

**Comment by kazupon** [comment]
Hi!
I've released unplugin-vue-i18n v0.6
https://github.com/intlify/bundle-tools/releases/tag/unplugin-vue-i18n%400.6.0

please check it!

**Comment by kentahama** [comment]
Thank you a lot for fixing the problem!
Now I can get appropriate error. I will close this PR.

**Comment by kazupon** [comment]
Happy coding! :)

**Pull request closed without merging**
